### ISSUE TITLE
New version of Ant without jai

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-orbit/orbit#17]
We need a new version of Ant in Orbit without Jai as we can't distribute Jai from EF - see [IP lab](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/5372#note_1052111)

**Comment by jonahgraham** [comment]
There have been two attempts to update Ant:

- https://git.eclipse.org/r/c/orbit/orbit-recipes/+/199491
- https://git.eclipse.org/r/c/orbit/orbit-recipes/+/199664

And there is some history in Bugzilla here - https://bugs.eclipse.org/bugs/show_bug.cgi?id=581386

I think https://git.eclipse.org/r/c/orbit/orbit-recipes/+/199664 is more progressed and should be completed and moved here as a PR.

@SarikaSinha you started doing the work in this area, are you able to complete it?

**Comment by SarikaSinha** [comment]
@jonahgraham 
I could not proceed after the build failure. How to brainstorm and find different approach to build it?

**Comment by jonahgraham** [comment]
@SarikaSinha 

I think there is a pattern to exclude that class file from the output jar so it doesn't end up on classpath (which leads to error).

I think you can do that with `recipe.excludes` properties to exclude the whole problematic class, here are a couple of examples:

https://github.com/eclipse/orbit/blob/935959313c2da621eb1b160eed8364302f0cc1bd/logging/ch.qos.logback.classic_1.2.3/pom.xml#L29

https://github.com/eclipse/orbit/blob/5429dddf21e8fa6ad4a88f4b272bea9008d4ceec/bouncycastle/org.bouncycastle.bcprov_1.72.0/pom.xml#L19-L20



Also see:

https://github.com/eclipse/orbit/blob/bc5de046ea2e6b148daf58393487e226fdd14c27/apache/ant/README.adoc#L28-L29

**Comment by jonahgraham** [comment]
Thanks for the update.

(Speaking as the Orbit PL): As the Ant dependency is from the Eclipse Project, to answer how long we can/should wait the Eclipse Project team needs to take that up with Eclipse IP team in https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/5372

(Speaking as an Eclipse Platform Committer): I will start that conversation in iplab :-)

**Comment by merks** [comment]
The 1.10.14 version is available:

- https://download.eclipse.org/tools/orbit/simrel/maven-bnd/milestone/latest
- https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/milestone/latest
