### ISSUE TITLE
Remove bundles that have OSGi metadata upstream

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-orbit/orbit#25]
For a long time Orbit's re-bundling was _the_ way to get third-party libraries from Maven into an Eclipse p2 consumable state.

For a while now there has been a better way for getting third-party dependencies that already contains OSGi metadata.  That is to use the M2E's maven target locations and sign the bundles with PGP instead of jarsigning. There has been much communication on mailing lists and in issues on this topic in the the last couple of years.

The next step now is to stop maintaining the Orbit bundles that rewrite the OSGi metadata when the upstream bundle has the OSGi metadata in it correctly already.

The goal is to have the first step of this process done for 2023-09 M1 by removing the bundles. In addition @merks's work in https://github.com/eclipse-oomph/oomph.incubator will be migrated into the Orbit project so that Orbit provides p2 repos with the PGP signed third-party dependencies already in them.

Here are the bundles that have valid OSGi metadata in the upstream version that we plan to remove. This list will be added to as we vet additional bundles.

- [x] #9 #26
- [x] #19 #24
- [x] #27
- [ ] #28
- [x] #29
- [x] #30
- [ ] SLF4J
- [ ] logback
- [ ] commons-logging
- [x] #33
- [x] #34
- [ ] #35
- [x] #36
- [ ] jakarta.servlet-api and jakarta.el-api (Eclipse Platform ships direct from Maven version older than versions in Orbit)
- [ ] #38
- [x] #39
- [ ] jackson (Eclipse platform consumes direct from Maven, but does not re-publish, other projects are publishing Orbit version to SimRel)
- [x] #40
- [ ] apache commons-collections 3  (Eclipse platform consumes direct from Maven, but does not re-publish, other projects are publishing Orbit version to SimRel)
- [x] #42
- [x] #43
- [ ] #44
- [ ] commons-codec
- [ ] commons-compress
- [ ] commons-io
- [ ] guava
- [x] #45
- [ ] guice aka com.google.inject
- [x] #46

**Comment by jonahgraham** [comment]
I will be adding to the description of this issue a check-list covering all the items we plan on removing.

**Comment by jonahgraham** [comment]
In the first instance I will be pruning out all the items listed in the target platforms for the projects consuming from maven central and contributing to simrel already, such as platform, tm4e, etc. See https://github.com/eclipse-oomph/oomph.incubator/tree/master/maven/org.eclipse.oomph.maven.generator/report for the source that I am using.

**Comment by jonahgraham** [comment]
- I have moved this work into a branch and reverted all the removals from main in #47 
- This had caused some unexpected disruption due to some projects consuming I-builds that needs to be resolved first

**Comment by merks** [comment]
We can remove all of com.github.jrn.* from Orbit

![image](https://github.com/eclipse-orbit/orbit/assets/208716/21fff63c-94db-4f69-93c3-dc35431ea02d)

See this for analysis:

https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/pull/213

The two that need wrapping are handled here:

https://github.com/eclipse-orbit/orbit-simrel/blob/93b4bc855b2881bd47f17032b99bfb2f2ed5c137/maven-bnd/tp/MavenBND.target#L148-L160

The rest that don't are here:

https://github.com/eclipse-orbit/orbit-simrel/blob/93b4bc855b2881bd47f17032b99bfb2f2ed5c137/maven-osgi/tp/Maven.target#L87-L130

**Comment by cdietrich** [comment]
Xtext uses classgraph 
Also aopalliance (used by guice) 
And junit 4.13.2
See https://github.com/eclipse-orbit/orbit-simrel/issues/4

**Comment by merks** [comment]
What is "classgraph"?

**Comment by merks** [comment]
Maybe this?

![image](https://github.com/eclipse-orbit/orbit/assets/208716/07dad254-0933-498c-a4c3-787be96287b1)

**Comment by HannesWell** [comment]
> Maybe this?

I believe that's the one, yes.

**Comment by cdietrich** [comment]
yes this is classgraph. it has osgi metadata as it looks like so we could update.
but i dont know when i can find time to work on it in Xtext side
if work is more than a bump

**Comment by jonahgraham** [comment]
Rather than handling it by removing bundles from EBR style Orbit (this repo) the new Orbit aggregation repo is excluding old bundles as they are replaced - see https://github.com/eclipse-orbit/orbit-simrel/blob/main/orbit-aggregation/orbit.aggr
