### ISSUE TITLE
Eliminate "Legacy" Bundle

### ISSUE THREAD

**Issue by merks** [eclipse-orbit/orbit#52]
In order to produce this aggregation:

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation

these really, really old bundles are dragged in:

![image](https://github.com/eclipse-orbit/orbit/assets/208716/6b80fedc-55e3-44ee-a1dc-2e4341d657ee)

These all need to be removed or replaced.

A bunch of these are dragged in to make batik happy, i.e., the 3 selected bundles above.  They could be replaced by one of these:

- https://repo1.maven.org/maven2/batik/batik-ext/1.6
- https://repo1.maven.org/maven2/xml-apis/xml-apis-ext/1.3.04/

But those things do not provide sources and I don't think it's okay to not provide sources. It's certainly not nice and not ideal.

Note that I tried to find if **anything** on Maven Central provides sources and have reached the conclusion that the only thing providing sources are the old Orbit source bundles themselves.

The problem isn't just that these are old, they also have package imports that could be satisfied by the JDK, but not when there is a version constraint because the JDK's packages are not versioned.

I would like to propose that we create a new Git repository to maintain bundles in source form for bundles that cannot be created by bundling a Maven Central artifact. Of course we want as few of those as possible!

I've prototyped the following repository contents:

![image](https://github.com/eclipse-orbit/orbit/assets/208716/c228230c-c9b2-47fa-9f32-56167ba09ebf)

I've take the three source bundles and combined them into a single bundle with the same combined contents as the above two Maven artifacts.

![image](https://github.com/eclipse-orbit/orbit/assets/208716/52b2be80-889e-4140-bf5b-89a3c3b32cb8)

If I use the resulting repository in the aggregation,  we can see that the new bundle eliminates the org.w3c.dom.events bundle too, it satisfies all the batik constraints, and it will allow us to eliminate the javax.xml bundle too.

https://github.com/eclipse-orbit/orbit/issues/48

@jonahgraham 

Shall I create a new `orbit-legacy` Git repository with the initial contents as outlined above to produce a p2 repository https://download.eclipse.org/tools/orbit/simrel/orbit-legacy that can then be used in the aggregation to replace using an actual older orbit ebr repository?  

Do you have any questions or concerns?

**Comment by merks** [comment]
I'm starting to wonder now about "everything has sources".  I don't find sources for org.apache.wsil4j anywhere.  So if there were a security problem, we'd be completely hosed and could not produce new binaries?

**Comment by merks** [comment]
I'm down to these legacy dependencies:

![image](https://github.com/eclipse-orbit/orbit/assets/208716/94fbd193-47e7-46cf-8bb1-47a37d81a19b)

The selected projects are source bundles that can be used to replace the legacy bundles, along with wsil4j for which no source exists and which appears to be repackaged from an older binary in repo.eclipse.org by EBR (and is a disaster waiting to happen, in my opinion).

**Comment by merks** [comment]
If I build that locally and replace the old Orbit EBR repo with that repo, the aggregation succeeds (with sources) like this:

![image](https://github.com/eclipse-orbit/orbit/assets/208716/38e47d4e-4cc3-4a4a-987c-82f1a6dbe32b)

**Comment by merks** [comment]
Here is the prototype temporarily checked into my personal repository:

https://github.com/merks/orbit-legacy/

**Comment by merks** [comment]
@jonahgraham 

I opened this iplab issue to ensure that we're properly following any and all applicable rules:

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9823

**Comment by jonahgraham** [comment]
> Shall I create a new orbit-legacy Git repository with the initial contents as outlined above to produce a p2 repository https://download.eclipse.org/tools/orbit/simrel/orbit-legacy that can then be used in the aggregation to replace using an actual older orbit ebr repository?

+1

> Do you have any questions or concerns?

No concerns. 

---

I want to point out how Orbit has handled items missing on Maven Central in the past, see https://github.com/eclipse-orbit/orbit/blob/main/Add-bundle.md#library-not-available-on-maven-central

That approach was simple - but has the obvious problem of little to no reproduciblty as the jars uploaded were built on user's machines.

I am not advocating for maintaining that going forward, but it is an important part of the historical puzzle .

**Comment by nitind** [comment]
It seems that the new org.apache.axis bundle is no longer a combination of org.apache.axis:axis:1.4 and org.apache.axis:axis-ant:1.4, but only contains the main axis artifact. I don't know if my Tycho 4 adoption builds were breaking before this Issue, but they certainly are now.

**Comment by merks** [comment]
@nitind 

Sorry about that.  I had no idea that was the case and should have looked more closely at the old bundle.  I don't think the maven-location approach can combine two libraries into one.    Providing a separate org.apache.axis.ant bundle is easy though and I think that does make more sense...

**Comment by nitind** [comment]
Thanks @merks , I've pushed changes adding with the new bundle in mind. The other failures I mentioned in passing are from org.junit failing to find org.hamcrest by package name and version; I do not know if it is related to that now being a split package.

**Comment by merks** [comment]
Note that I've rebuilt newer versions of **today** that should more closely (exactly) match what was produced before based on this discussion:

https://github.com/eclipse-orbit/orbit-simrel/discussions/5

**Comment by nitind** [comment]
We don't seem to be at the drop-in replacement stage yet.
`[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.0:validate-classpath (default-validate-classpath) on project org.eclipse.wst.common.snippets.tests: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:4.0.0:validate-classpath failed: org.osgi.framework.BundleException: Bundle org.eclipse.wst.common.snippets.tests cannot be resolved:org.eclipse.wst.common.snippets.tests [113]
[ERROR]   Unresolved requirement: Require-Bundle: org.junit; bundle-version="3.8.2"
[ERROR]     -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230725-0701"
[ERROR]        org.junit [107]
[ERROR]          Unresolved requirement: Import-Package: org.hamcrest; version="1.3.0"
[ERROR] -> [Help 1]
`

**Comment by merks** [comment]
The org.junit bundles has these two  things:
```
Import-Package                          org.hamcrest.core;version="1.3"
                                        org.hamcrest;version="1.3"
Manifest-Version                        1.0
Originally-Created-By                   Apache Maven 3.1.1
Require-Bundle                          org.hamcrest.core;bundle-version="1.3.0";resolution:=optional;visibility:=reexport;x-installation:=greedy
```
The older version had a **non-optional** requirement on org.hamcrest.core, but there is a new bundle org.hamcrest version 2.2 that will also make org.junit happy and we want people to migrate to that newer one.

The Xtext build and the Platform build had and I told them make sure that org.hamcrest.core  is explicitly in the target platform.

**Comment by merks** [comment]
@nitind 

I've gone through what look like ancient javax things here and systematically found jakarta replacements for this:

![image](https://github.com/eclipse-orbit/orbit/assets/208716/c95896d1-645c-4610-9fcd-b10ef7c28db0)

I've filtered out all javax bundle coming from orbit ebr.

The nightly build has all the replacements:

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/latest/index.html

Including for the really ancient legacy things for which there was no source.

If there is something ancient that you still need, please open an issue requesting what's missing.
