### ISSUE TITLE
Move this repo to `eclipse-orbit` organization along with Eclipse EBR once `eclipse-orbit` can be registered.

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-orbit/orbit#6]

**Comment by jonahgraham** [comment]
From [Eclipse Webmaster in gitlab](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2438#note_1099073):

> We can handle moving these repos into a separate organization separately as I'm still currently unable to claim the eclipse-orbit name.

**Comment by HannesWell** [comment]
What is the status here?

I think a repo for 'wrapped' maven artifacts (as suggested in https://github.com/merks/simrel-maven/issues/5) would be best placed in a eclipse-orbit orga.

**Comment by jonahgraham** [comment]
> What is the status here?

Webmasters are waiting to claim the name once it becomes available. See https://github.com/eclipse/orbit/issues/6#issuecomment-1494786740 - IIRC it is a 3 month wait.


> I think a repo for 'wrapped' maven artifacts (as suggested in [merks/simrel-maven#5](https://github.com/merks/simrel-maven/issues/5)) would be best placed in a eclipse-orbit orga.

Yes!

**Comment by jonahgraham** [comment]
Progress is afoot - EF now owns eclipse-orbit - track progress here - https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3198

**Comment by merks** [comment]
We have arrived at our destination.
